---
Name: yplay-config
---
SilverStripe\SpamProtection\Extension\FormSpamProtectionExtension:
  default_spam_protector: UndefinedOffset\NoCaptcha\Forms\NocaptchaProtector

UndefinedOffset\NoCaptcha\Forms\NocaptchaField:
    site_key: "6LdUrl8UAAAAABu20XIulQ4Tcvn8bujn2aUWXYP_" #Your site key (required)
    secret_key: "6LdUrl8UAAAAANcovcXCC2yHJBAIsUxezeuMRWE3" #Your secret key (required)
    verify_ssl: true #Allows you to disable php-curl's SSL peer verification by setting this to false (optional, defaults to true)
    default_theme: "light" #Default theme color (optional, light or dark, defaults to light)
    default_type: "image" #Default captcha type (optional, image or audio, defaults to image)
    default_size: "invisible" #Default size (optional, normal, compact or invisible, defaults to normal)
    default_badge: "bottomright" #Default badge position (bottomright, bottomleft or inline, defaults to bottomright)
    #proxy_server: "" #Your proxy server address (optional)
    #proxy_auth: "" #Your proxy server authentication information (optional)


SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'yplay'
    - '$default'
SilverStripe\i18n\i18n:
  default_locale: 'de_DE'


PageController:
  extensions:
    - 'CustomPageControllerExtension'

Page:
  extensions:
    - 'CustomPageExtension'