---
Name: yplay-shop-config
---
BaseBlockExtension:
  blocks:
    - ProductBlock
    - ShopFinderBlock
    - MarketingBlock
    #- TeasingBlock
    - HDSmartcardBlock
    - PayTVBlock
    - CustomerMoveBlock
  children_blocks:
    - ProductBlock
    - MarketingBlock
    #- TeasingBlock
    - HDSmartcardBlock
    - PayTVBlock
    - CustomerMoveBlock

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - ShopConfigExtension

PageController:
  extensions:
    - YplaYPageControllerExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - yplay-shop/css/yplay_shop.css