---
Name: deskall-shop
After:
    - '#deskall-divers'
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-shop

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigPayPalExtension

SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - ShopOrderItemRequestExtension

BaseBlockExtension:
  blocks:
    - ProductBlock

Page:
  extensions:
    - DeskallShopPageExtension

LayoutBlock:
  extensions:
    - ShopMenuBlockExtension